name: "Perform common steps"
description: "Performs common steps over the workflows"
runs:
    using: "composite"
    steps:
        - name: ⚙ Setup .NET SDK ⚙
          uses: actions/setup-dotnet@v4
          with:
              dotnet-version: '8.0.x'

        - name: ♻ NuGet Cache ♻
          uses: actions/cache@v3
          with:
              path: ${{ env.NUGET_PACKAGES }}
              key: ${{ runner.os }}.nuget.${{ hashFiles('**/*.csproj') }}

        - name: 🔄 Restore Nuget Packages 🔄
          shell: bash
          run: dotnet restore
